version: '3.3'

services:
  django:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend/:/usr/src/backend/
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:15.4-alpine3.18
    environment:
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=qweasd123
      - POSTGRES_DB=django_db
    volumes:
      - postgres_data:/var/lib/postgres/data/

volumes:
  postgres_data:
